# Docker Compose file for TurtleBot3 Behavior Examples
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:
  # Base image containing dependencies.
  base:
    image: turtlebot3_behavior:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Allows graphical programs in the container.
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
    # Mount the source code
    - ./tb3_autonomy:/overlay_ws/src/tb3_autonomy:rw
    - ./tb3_worlds:/overlay_ws/src/tb3_worlds:rw
    # Allows graphical programs in the container.
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: sleep infinity
  
  # Overlay image containing the example source code.
  overlay:
    extends: base
    image: turtlebot3_behavior:overlay
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay
    command: sleep infinity

  # Runs basic TurtleBot3 simulation
  sim:
    extends: overlay
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

  # Demo world
  demo-world:
    extends: overlay
    command: ros2 launch tb3_worlds tb3_demo_world.launch.py

  # Behavior demo using Python and py_trees
  demo-behavior-py:
    extends: overlay
    command: >
      ros2 launch tb3_autonomy tb3_demo_behavior_py.launch.py
      tree_type:=${BT_TYPE:?}
      enable_vision:=${ENABLE_VISION:?}
      target_color:=${TARGET_COLOR:?}

  # Behavior demo using C++ and BehaviorTree.CPP
  demo-behavior-cpp:
    extends: overlay
    command: >
      ros2 launch tb3_autonomy tb3_demo_behavior_cpp.launch.py
      tree_type:=${BT_TYPE:?}
      enable_vision:=${ENABLE_VISION:?}
      target_color:=${TARGET_COLOR:?}
